import { Platform, StyleSheet } from 'react-native';

export const wizardStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  wizardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2A2A2A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardStepInfo: {
    flex: 1,
    alignItems: 'center',
  },
  wizardStepLabel: {
    color: '#666',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  wizardStepTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 2,
  },
  wizardProgressBg: {
    height: 4,
    backgroundColor: '#2A2A2A',
    marginHorizontal: 20,
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 8,
  },
  wizardProgressFill: {
    height: '100%',
    backgroundColor: '#4C91FF',
    borderRadius: 2,
  },
  stepBody: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
  },
  wizardQuestion: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 20,
  },
  wizardSubtext: {
    color: '#777',
    fontSize: 14,
    marginTop: -12,
    marginBottom: 20,
  },
  fixedFooter: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#2F2F2F',
    backgroundColor: '#101010',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 10,
  },
  addExerciseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1E1E1E',
    borderWidth: 1,
    borderColor: '#4C91FF',
    borderStyle: 'dashed',
    borderRadius: 14,
    paddingVertical: 14,
  },
  addExerciseBtnText: {
    color: '#4C91FF',
    fontSize: 16,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    paddingHorizontal: 24,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    borderStyle: 'dashed',
    backgroundColor: '#141414',
    marginBottom: 8,
  },
  emptyStateText: {
    color: '#888',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 12,
  },
  wizardNextBtn: {
    backgroundColor: '#4C91FF',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  wizardNextBtnText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  wizardCreateBtn: {
    backgroundColor: '#51CF66',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  wizardBtnRow: {
    flexDirection: 'row',
    gap: 12,
  },
  wizardBackBtn: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    backgroundColor: '#2A2A2A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardBackBtnText: {
    color: '#CCCCCC',
    fontSize: 16,
    fontWeight: '600',
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  searchInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    paddingVertical: 14,
    paddingHorizontal: 10,
  },
  suggestionList: {
    marginTop: 8,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    overflow: 'hidden',
  },
  suggestionItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  suggestionItemText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  suggestionCustomText: {
    color: '#4C91FF',
    fontSize: 14,
    fontWeight: '600',
  },
  colorRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  colorDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  colorDotSelected: {
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  wizardExRow: {
    backgroundColor: '#1A1A1A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  wizardExTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  wizardExNumber: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#4C91FF20',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  wizardExNumberText: {
    color: '#4C91FF',
    fontSize: 12,
    fontWeight: '700',
  },
  wizardExName: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  wizardExRemove: {
    padding: 6,
    marginLeft: 8,
  },
  wizardExControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  wizardStepperGroup: {
    alignItems: 'center',
  },
  wizardStepperLabel: {
    color: '#888',
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  wizardStepperX: {
    color: '#555',
    fontSize: 16,
    marginTop: 16,
  },
  wizardStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 10,
    overflow: 'hidden',
  },
  wizardStepperBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardStepperBtnText: {
    color: '#4C91FF',
    fontSize: 18,
    fontWeight: '700',
  },
  wizardStepperValue: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    paddingHorizontal: 10,
    minWidth: 36,
    textAlign: 'center',
  },
  wizardPRRow: {
    backgroundColor: '#1A1A1A',
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  wizardPRHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  wizardPRName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  wizardPRBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#2A2200',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  wizardPRBadgeText: {
    color: '#FFB547',
    fontSize: 12,
    fontWeight: '600',
  },
  wizardPRInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  wizardPRInputLabel: {
    color: '#777',
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 6,
  },
  wizardPRInput: {
    backgroundColor: '#2A2A2A',
    borderRadius: 10,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    paddingVertical: 10,
    paddingHorizontal: 14,
    textAlign: 'center',
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  pickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#2A2A2A',
  },
  pickerTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  pickerDoneBtn: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  pickerDoneText: {
    color: '#4C91FF',
    fontSize: 16,
    fontWeight: '700',
  },
  pickerSearchSection: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  categoryPillsContainer: {
    marginTop: 10,
    marginBottom: 8,
    flexGrow: 0,
    minHeight: 44,
  },
  categoryPillsScroll: {
    gap: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    paddingVertical: 4,
  },
  categoryPill: {
    backgroundColor: '#2A2A2A',
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: 38,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryPillText: {
    color: '#CCCCCC',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  pickerResultItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  pickerResultName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
    flex: 1,
  },
  pickerResultCategory: {
    color: '#666',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 8,
    backgroundColor: '#1E1E1E',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  pickerCustomRow: {
    borderBottomWidth: 0,
  },
  pickerCustomText: {
    color: '#4C91FF',
    fontSize: 14,
    fontWeight: '600',
  },
  pickerAddedBadge: {
    color: '#51CF66',
    fontSize: 12,
    fontWeight: '700',
  },
  aiQuizContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
    flexGrow: 1,
  },
  aiQuizBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  aiQuizBadgeText: {
    color: '#A78BFA',
    fontSize: 13,
    fontWeight: '700',
  },
  aiOptionsCol: {
    gap: 10,
    marginBottom: 28,
  },
  aiOptionCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  aiOptionCardSelected: {
    borderColor: '#845EF7',
    backgroundColor: '#2B2248',
  },
  aiOptionLabel: {
    color: '#CCCCCC',
    fontSize: 16,
    fontWeight: '600',
  },
  aiOptionLabelSelected: {
    color: '#FFFFFF',
  },
  aiOptionBlurb: {
    color: '#8B8B8B',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    fontWeight: '500',
  },
  aiGeneratingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    paddingBottom: 80,
  },
  aiGeneratingTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    marginTop: 20,
  },
  aiGeneratingSub: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
  },
});
