# Generated by Django 5.1.4 on 2026-02-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workouttemplate_templateexercise_personalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutfeed',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='core.workouttemplate'),
        ),
    ]
