# Generated by Django 5.1.4 on 2026-02-17 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workoutfeed_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '❤️'), ('fire', '🔥'), ('muscle', '💪'), ('clap', '👏'), ('wow', '😮')], default='like', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.workoutfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reactions', to='core.profile')),
            ],
            options={
                'unique_together': {('feed', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='FeedLike',
        ),
    ]
