# Generated by Django 5.1.4 on 2026-03-17 18:42

from django.db import migrations


def migrate_friendships_to_follows(apps, schema_editor):
    """For each accepted friendship, create Follow records in both directions."""
    Friendship = apps.get_model('core', 'Friendship')
    Follow = apps.get_model('core', 'Follow')

    for f in Friendship.objects.filter(status='accepted'):
        Follow.objects.get_or_create(follower=f.user, following=f.friend)
        Follow.objects.get_or_create(follower=f.friend, following=f.user)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_challenge_options_challenge_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_friendships_to_follows, migrations.RunPython.noop),
    ]
