# Generated by Django 5.2.12 on 2026-03-26 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dailytip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLibraryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('influencer', 'Influencer'), ('technical', 'Technical'), ('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('conditioning', 'Conditioning')], default='technical', max_length=40)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('source_name', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(default='#4C91FF', max_length=7)),
                ('icon', models.CharField(default='dumbbell', max_length=50)),
                ('exercises', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='core_workou_is_acti_c3a21f_idx'), models.Index(fields=['category'], name='core_workou_categor_a1ab46_idx')],
            },
        ),
    ]
