from django.db import migrations, models


def seed_expanded_library(apps, schema_editor):
    WorkoutLibraryTemplate = apps.get_model('core', 'WorkoutLibraryTemplate')

    seed_data = [
        # Influencer-inspired templates (attributed)
        {
            'name': 'Sam Sulek Push Day',
            'category': 'influencer',
            'subtitle': 'Inspired by Sam Sulek push sessions',
            'source_name': 'Sam Sulek (YouTube)',
            'source_url': 'https://www.youtube.com/@sam_sulek',
            'color': '#FF6B6B',
            'sort_order': 1,
            'exercises': [
                {'name': 'Incline Dumbbell Press', 'default_sets': 4, 'default_reps': 8, 'order': 0},
                {'name': 'Machine Chest Press', 'default_sets': 4, 'default_reps': 10, 'order': 1},
                {'name': 'Cable Fly', 'default_sets': 3, 'default_reps': 12, 'order': 2},
                {'name': 'Seated Dumbbell Shoulder Press', 'default_sets': 4, 'default_reps': 8, 'order': 3},
                {'name': 'Lateral Raise', 'default_sets': 4, 'default_reps': 15, 'order': 4},
                {'name': 'Tricep Pushdown', 'default_sets': 4, 'default_reps': 12, 'order': 5},
            ],
        },
        {
            'name': 'Sam Sulek Pull Day',
            'category': 'influencer',
            'subtitle': 'Inspired by Sam Sulek pull sessions',
            'source_name': 'Sam Sulek (YouTube)',
            'source_url': 'https://www.youtube.com/@sam_sulek',
            'color': '#845EF7',
            'sort_order': 2,
            'exercises': [
                {'name': 'Lat Pulldown', 'default_sets': 4, 'default_reps': 10, 'order': 0},
                {'name': 'Chest-Supported Row', 'default_sets': 4, 'default_reps': 10, 'order': 1},
                {'name': 'Seated Cable Row', 'default_sets': 3, 'default_reps': 12, 'order': 2},
                {'name': 'Face Pull', 'default_sets': 3, 'default_reps': 15, 'order': 3},
                {'name': 'EZ-Bar Curl', 'default_sets': 4, 'default_reps': 10, 'order': 4},
                {'name': 'Hammer Curl', 'default_sets': 3, 'default_reps': 12, 'order': 5},
            ],
        },
        {
            'name': 'Jeff Nippard Upper (Powerbuilding)',
            'category': 'influencer',
            'subtitle': 'Inspired by Jeff Nippard powerbuilding style',
            'source_name': 'Jeff Nippard',
            'source_url': 'https://jeffnippard.com/',
            'color': '#4C91FF',
            'sort_order': 3,
            'exercises': [
                {'name': 'Bench Press', 'default_sets': 4, 'default_reps': 5, 'order': 0},
                {'name': 'Weighted Pull-Up', 'default_sets': 4, 'default_reps': 6, 'order': 1},
                {'name': 'Overhead Press', 'default_sets': 3, 'default_reps': 6, 'order': 2},
                {'name': 'Barbell Row', 'default_sets': 3, 'default_reps': 8, 'order': 3},
                {'name': 'Incline Dumbbell Press', 'default_sets': 3, 'default_reps': 10, 'order': 4},
                {'name': 'EZ-Bar Curl', 'default_sets': 3, 'default_reps': 10, 'order': 5},
            ],
        },
        {
            'name': 'Jeff Nippard Lower (Powerbuilding)',
            'category': 'influencer',
            'subtitle': 'Inspired by Jeff Nippard lower-body structure',
            'source_name': 'Jeff Nippard',
            'source_url': 'https://jeffnippard.com/',
            'color': '#FF922B',
            'sort_order': 4,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 4, 'default_reps': 5, 'order': 0},
                {'name': 'Romanian Deadlift', 'default_sets': 4, 'default_reps': 6, 'order': 1},
                {'name': 'Leg Press', 'default_sets': 3, 'default_reps': 10, 'order': 2},
                {'name': 'Leg Curl', 'default_sets': 3, 'default_reps': 12, 'order': 3},
                {'name': 'Walking Lunge', 'default_sets': 3, 'default_reps': 12, 'order': 4},
                {'name': 'Seated Calf Raise', 'default_sets': 4, 'default_reps': 15, 'order': 5},
            ],
        },
        {
            'name': 'Arnold Split Chest & Back',
            'category': 'influencer',
            'subtitle': 'Classic Arnold split pairing',
            'source_name': 'Arnold Schwarzenegger',
            'source_url': 'https://www.bodybuilding.com/author/arnold-schwarzenegger',
            'color': '#CC5DE8',
            'sort_order': 5,
            'exercises': [
                {'name': 'Bench Press', 'default_sets': 5, 'default_reps': 8, 'order': 0},
                {'name': 'Incline Bench Press', 'default_sets': 4, 'default_reps': 10, 'order': 1},
                {'name': 'Dumbbell Fly', 'default_sets': 4, 'default_reps': 12, 'order': 2},
                {'name': 'Pull-Up', 'default_sets': 5, 'default_reps': 8, 'order': 3},
                {'name': 'Barbell Row', 'default_sets': 4, 'default_reps': 10, 'order': 4},
                {'name': 'Deadlift', 'default_sets': 3, 'default_reps': 5, 'order': 5},
            ],
        },
        {
            'name': 'CBum Leg Day (Classic Physique)',
            'category': 'influencer',
            'subtitle': 'Inspired by CBum high-intent quad/ham day',
            'source_name': 'Chris Bumstead',
            'source_url': 'https://www.youtube.com/@ChrisBumstead',
            'color': '#FFB547',
            'sort_order': 6,
            'exercises': [
                {'name': 'Hack Squat', 'default_sets': 4, 'default_reps': 10, 'order': 0},
                {'name': 'Leg Press', 'default_sets': 4, 'default_reps': 12, 'order': 1},
                {'name': 'Romanian Deadlift', 'default_sets': 4, 'default_reps': 8, 'order': 2},
                {'name': 'Leg Extension', 'default_sets': 3, 'default_reps': 15, 'order': 3},
                {'name': 'Seated Leg Curl', 'default_sets': 3, 'default_reps': 15, 'order': 4},
                {'name': 'Standing Calf Raise', 'default_sets': 4, 'default_reps': 15, 'order': 5},
            ],
        },
        {
            'name': 'Athlean-X Athletic Upper',
            'category': 'influencer',
            'subtitle': 'Athletic strength with shoulder health focus',
            'source_name': 'ATHLEAN-X',
            'source_url': 'https://athleanx.com/',
            'color': '#20C997',
            'sort_order': 7,
            'exercises': [
                {'name': 'Incline Dumbbell Press', 'default_sets': 4, 'default_reps': 8, 'order': 0},
                {'name': 'Single-Arm Cable Row', 'default_sets': 4, 'default_reps': 10, 'order': 1},
                {'name': 'Landmine Press', 'default_sets': 3, 'default_reps': 10, 'order': 2},
                {'name': 'Face Pull', 'default_sets': 4, 'default_reps': 15, 'order': 3},
                {'name': 'Cable Curl', 'default_sets': 3, 'default_reps': 12, 'order': 4},
                {'name': 'Tricep Rope Pushdown', 'default_sets': 3, 'default_reps': 12, 'order': 5},
            ],
        },

        # Technical templates
        {
            'name': 'Classic Push Day',
            'category': 'technical',
            'subtitle': 'Structured chest/shoulders/triceps split',
            'source_name': 'NSCA-style programming',
            'source_url': 'https://www.nsca.com/education/articles/kinetic-select/push-pull-training/',
            'color': '#4C91FF',
            'sort_order': 20,
            'exercises': [
                {'name': 'Bench Press', 'default_sets': 4, 'default_reps': 6, 'order': 0},
                {'name': 'Incline Dumbbell Press', 'default_sets': 3, 'default_reps': 8, 'order': 1},
                {'name': 'Overhead Press', 'default_sets': 3, 'default_reps': 8, 'order': 2},
                {'name': 'Lateral Raise', 'default_sets': 3, 'default_reps': 15, 'order': 3},
                {'name': 'Skull Crusher', 'default_sets': 3, 'default_reps': 10, 'order': 4},
            ],
        },
        {
            'name': 'Classic Pull Day',
            'category': 'technical',
            'subtitle': 'Back and biceps progression template',
            'source_name': 'NSCA-style programming',
            'source_url': 'https://www.nsca.com/education/articles/kinetic-select/push-pull-training/',
            'color': '#845EF7',
            'sort_order': 21,
            'exercises': [
                {'name': 'Deadlift', 'default_sets': 3, 'default_reps': 5, 'order': 0},
                {'name': 'Pull-Up', 'default_sets': 4, 'default_reps': 8, 'order': 1},
                {'name': 'Barbell Row', 'default_sets': 4, 'default_reps': 8, 'order': 2},
                {'name': 'Face Pull', 'default_sets': 3, 'default_reps': 15, 'order': 3},
                {'name': 'Barbell Curl', 'default_sets': 3, 'default_reps': 10, 'order': 4},
            ],
        },
        {
            'name': 'Leg Day Strength',
            'category': 'strength',
            'subtitle': 'Compound-heavy lower body day',
            'source_name': 'Starting Strength principles',
            'source_url': 'https://startingstrength.com/',
            'color': '#FF922B',
            'sort_order': 22,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 5, 'default_reps': 5, 'order': 0},
                {'name': 'Romanian Deadlift', 'default_sets': 4, 'default_reps': 8, 'order': 1},
                {'name': 'Leg Press', 'default_sets': 3, 'default_reps': 10, 'order': 2},
                {'name': 'Walking Lunge', 'default_sets': 3, 'default_reps': 12, 'order': 3},
                {'name': 'Seated Calf Raise', 'default_sets': 4, 'default_reps': 15, 'order': 4},
            ],
        },
        {
            'name': 'Upper / Lower - Upper A',
            'category': 'technical',
            'subtitle': 'Balanced upper day for 4-day split',
            'source_name': 'Upper/Lower split standard',
            'source_url': 'https://www.strongerbyscience.com/program-bundle/',
            'color': '#51CF66',
            'sort_order': 23,
            'exercises': [
                {'name': 'Bench Press', 'default_sets': 4, 'default_reps': 6, 'order': 0},
                {'name': 'Barbell Row', 'default_sets': 4, 'default_reps': 8, 'order': 1},
                {'name': 'Overhead Press', 'default_sets': 3, 'default_reps': 8, 'order': 2},
                {'name': 'Lat Pulldown', 'default_sets': 3, 'default_reps': 10, 'order': 3},
                {'name': 'Tricep Pushdown', 'default_sets': 3, 'default_reps': 12, 'order': 4},
                {'name': 'Hammer Curl', 'default_sets': 3, 'default_reps': 12, 'order': 5},
            ],
        },
        {
            'name': 'Upper / Lower - Lower A',
            'category': 'technical',
            'subtitle': 'Balanced lower day for 4-day split',
            'source_name': 'Upper/Lower split standard',
            'source_url': 'https://www.strongerbyscience.com/program-bundle/',
            'color': '#20C997',
            'sort_order': 24,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 4, 'default_reps': 6, 'order': 0},
                {'name': 'Romanian Deadlift', 'default_sets': 3, 'default_reps': 8, 'order': 1},
                {'name': 'Bulgarian Split Squat', 'default_sets': 3, 'default_reps': 10, 'order': 2},
                {'name': 'Leg Curl', 'default_sets': 3, 'default_reps': 12, 'order': 3},
                {'name': 'Standing Calf Raise', 'default_sets': 4, 'default_reps': 12, 'order': 4},
            ],
        },
        {
            'name': 'PHUL Upper Power',
            'category': 'strength',
            'subtitle': 'Power Hypertrophy Upper day',
            'source_name': 'PHUL framework',
            'source_url': 'https://www.muscleandstrength.com/workouts/phul-workout',
            'color': '#3B82F6',
            'sort_order': 25,
            'exercises': [
                {'name': 'Bench Press', 'default_sets': 4, 'default_reps': 4, 'order': 0},
                {'name': 'Barbell Row', 'default_sets': 4, 'default_reps': 5, 'order': 1},
                {'name': 'Overhead Press', 'default_sets': 3, 'default_reps': 5, 'order': 2},
                {'name': 'Weighted Pull-Up', 'default_sets': 3, 'default_reps': 6, 'order': 3},
                {'name': 'Barbell Curl', 'default_sets': 3, 'default_reps': 8, 'order': 4},
                {'name': 'Skull Crusher', 'default_sets': 3, 'default_reps': 8, 'order': 5},
            ],
        },
        {
            'name': 'PHUL Lower Power',
            'category': 'strength',
            'subtitle': 'Power Hypertrophy Lower day',
            'source_name': 'PHUL framework',
            'source_url': 'https://www.muscleandstrength.com/workouts/phul-workout',
            'color': '#F97316',
            'sort_order': 26,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 4, 'default_reps': 4, 'order': 0},
                {'name': 'Deadlift', 'default_sets': 3, 'default_reps': 4, 'order': 1},
                {'name': 'Leg Press', 'default_sets': 3, 'default_reps': 8, 'order': 2},
                {'name': 'Leg Curl', 'default_sets': 3, 'default_reps': 10, 'order': 3},
                {'name': 'Seated Calf Raise', 'default_sets': 4, 'default_reps': 10, 'order': 4},
            ],
        },
        {
            'name': 'Full Body 3x - Session A',
            'category': 'technical',
            'subtitle': 'Novice-friendly full body structure',
            'source_name': 'StrongLifts / linear progression style',
            'source_url': 'https://stronglifts.com/5x5/',
            'color': '#0EA5E9',
            'sort_order': 27,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 5, 'default_reps': 5, 'order': 0},
                {'name': 'Bench Press', 'default_sets': 5, 'default_reps': 5, 'order': 1},
                {'name': 'Barbell Row', 'default_sets': 5, 'default_reps': 5, 'order': 2},
                {'name': 'Plank', 'default_sets': 3, 'default_reps': 45, 'order': 3},
            ],
        },
        {
            'name': 'Full Body 3x - Session B',
            'category': 'technical',
            'subtitle': 'Alternating full body progression day',
            'source_name': 'StrongLifts / linear progression style',
            'source_url': 'https://stronglifts.com/5x5/',
            'color': '#14B8A6',
            'sort_order': 28,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 5, 'default_reps': 5, 'order': 0},
                {'name': 'Overhead Press', 'default_sets': 5, 'default_reps': 5, 'order': 1},
                {'name': 'Deadlift', 'default_sets': 1, 'default_reps': 5, 'order': 2},
                {'name': 'Hanging Leg Raise', 'default_sets': 3, 'default_reps': 10, 'order': 3},
            ],
        },
        {
            'name': '5x5 Strength Day',
            'category': 'strength',
            'subtitle': 'Classic low-rep barbell strength block',
            'source_name': 'StrongLifts',
            'source_url': 'https://stronglifts.com/5x5/',
            'color': '#2563EB',
            'sort_order': 29,
            'exercises': [
                {'name': 'Back Squat', 'default_sets': 5, 'default_reps': 5, 'order': 0},
                {'name': 'Bench Press', 'default_sets': 5, 'default_reps': 5, 'order': 1},
                {'name': 'Barbell Row', 'default_sets': 5, 'default_reps': 5, 'order': 2},
            ],
        },
        {
            'name': 'Hypertrophy Push (10-15 reps)',
            'category': 'hypertrophy',
            'subtitle': 'Volume-focused push template',
            'source_name': 'RP-style hypertrophy principles',
            'source_url': 'https://rpstrength.com/',
            'color': '#EC4899',
            'sort_order': 30,
            'exercises': [
                {'name': 'Incline Dumbbell Press', 'default_sets': 4, 'default_reps': 10, 'order': 0},
                {'name': 'Machine Chest Press', 'default_sets': 4, 'default_reps': 12, 'order': 1},
                {'name': 'Cable Fly', 'default_sets': 3, 'default_reps': 15, 'order': 2},
                {'name': 'Dumbbell Shoulder Press', 'default_sets': 3, 'default_reps': 10, 'order': 3},
                {'name': 'Lateral Raise', 'default_sets': 4, 'default_reps': 15, 'order': 4},
                {'name': 'Tricep Rope Pushdown', 'default_sets': 4, 'default_reps': 12, 'order': 5},
            ],
        },
        {
            'name': 'Hypertrophy Pull (10-15 reps)',
            'category': 'hypertrophy',
            'subtitle': 'Volume-focused pull template',
            'source_name': 'RP-style hypertrophy principles',
            'source_url': 'https://rpstrength.com/',
            'color': '#8B5CF6',
            'sort_order': 31,
            'exercises': [
                {'name': 'Lat Pulldown', 'default_sets': 4, 'default_reps': 10, 'order': 0},
                {'name': 'Chest-Supported Row', 'default_sets': 4, 'default_reps': 12, 'order': 1},
                {'name': 'Single-Arm Cable Row', 'default_sets': 3, 'default_reps': 12, 'order': 2},
                {'name': 'Face Pull', 'default_sets': 3, 'default_reps': 15, 'order': 3},
                {'name': 'Incline Dumbbell Curl', 'default_sets': 3, 'default_reps': 12, 'order': 4},
                {'name': 'Hammer Curl', 'default_sets': 3, 'default_reps': 12, 'order': 5},
            ],
        },
        {
            'name': 'Technical HIIT Circuit',
            'category': 'conditioning',
            'subtitle': 'Conditioning + core in minimal time',
            'source_name': 'ACSM HIIT principles',
            'source_url': 'https://www.acsm.org/',
            'color': '#20C997',
            'sort_order': 32,
            'exercises': [
                {'name': 'Assault Bike', 'default_sets': 6, 'default_reps': 30, 'order': 0},
                {'name': 'Burpee', 'default_sets': 4, 'default_reps': 12, 'order': 1},
                {'name': 'Kettlebell Swing', 'default_sets': 4, 'default_reps': 20, 'order': 2},
                {'name': 'Mountain Climber', 'default_sets': 4, 'default_reps': 30, 'order': 3},
                {'name': 'Plank', 'default_sets': 3, 'default_reps': 60, 'order': 4},
            ],
        },
        {
            'name': 'EMOM 20 Conditioning',
            'category': 'conditioning',
            'subtitle': 'Every-minute-on-the-minute conditioning',
            'source_name': 'CrossFit style conditioning',
            'source_url': 'https://www.crossfit.com/workout',
            'color': '#10B981',
            'sort_order': 33,
            'exercises': [
                {'name': 'Rowing Machine', 'default_sets': 5, 'default_reps': 200, 'order': 0},
                {'name': 'Box Jump', 'default_sets': 5, 'default_reps': 12, 'order': 1},
                {'name': 'Push-Up', 'default_sets': 5, 'default_reps': 15, 'order': 2},
                {'name': 'Air Squat', 'default_sets': 5, 'default_reps': 20, 'order': 3},
            ],
        },
        {
            'name': 'Sprint Intervals',
            'category': 'conditioning',
            'subtitle': 'Track or treadmill sprint protocol',
            'source_name': 'NSCA conditioning standards',
            'source_url': 'https://www.nsca.com/',
            'color': '#F43F5E',
            'sort_order': 34,
            'exercises': [
                {'name': 'Sprint', 'default_sets': 10, 'default_reps': 20, 'order': 0},
                {'name': 'Walk Recovery', 'default_sets': 10, 'default_reps': 60, 'order': 1},
                {'name': 'Plank', 'default_sets': 3, 'default_reps': 45, 'order': 2},
            ],
        },
        {
            'name': 'Core & Mobility Reset',
            'category': 'technical',
            'subtitle': 'Low-impact day for recovery and trunk strength',
            'source_name': 'NASM corrective exercise concepts',
            'source_url': 'https://www.nasm.org/',
            'color': '#64748B',
            'sort_order': 35,
            'exercises': [
                {'name': 'Dead Bug', 'default_sets': 3, 'default_reps': 12, 'order': 0},
                {'name': 'Side Plank', 'default_sets': 3, 'default_reps': 30, 'order': 1},
                {'name': 'Pallof Press', 'default_sets': 3, 'default_reps': 12, 'order': 2},
                {'name': 'Hip Flexor Stretch', 'default_sets': 3, 'default_reps': 30, 'order': 3},
                {'name': 'Thoracic Rotation', 'default_sets': 3, 'default_reps': 10, 'order': 4},
            ],
        },
    ]

    for payload in seed_data:
        WorkoutLibraryTemplate.objects.update_or_create(
            name=payload['name'],
            defaults=payload,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workoutlibrarytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlibrarytemplate',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RunPython(seed_expanded_library, migrations.RunPython.noop),
    ]
