# Generated by Django 5.2.12 on 2026-07-16 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_revenueevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=200)),
                ('total_sets', models.IntegerField(default=0)),
                ('total_reps', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_stats', to='core.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-total_reps'], name='core_exerci_user_id_fe8279_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise_name'), name='uniq_user_exercise_stat')],
            },
        ),
    ]
